"""Predefined rulesets for common use cases."""

RULESETS = {
    "python-safety": {
        "description": "Python best practices and safety",
        "rules": [
            {"type": "regex", "pattern": r"^pip3? install", "description": "Use uv instead of pip", "action": "warn", "tool": "Bash", "solution": "uv add"},
            {"type": "regex", "pattern": r"^python [^3]", "description": "Use python3 explicitly", "action": "warn", "tool": "Bash", "solution": "python3"},
            {"type": "regex", "pattern": r"rm -rf /", "description": "Dangerous rm command", "action": "block", "tool": "Bash"},
        ],
    },
    "git-safety": {
        "description": "Prevent dangerous git operations",
        "rules": [
            {"type": "regex", "pattern": r"git push.*(--force|-f)", "description": "No force push", "action": "block", "tool": "Bash"},
            {"type": "regex", "pattern": r"git reset --hard", "description": "Dangerous reset", "action": "warn", "tool": "Bash"},
        ],
    },
    "secrets": {
        "description": "Block hardcoded secrets",
        "rules": [
            {"type": "regex", "pattern": r"(api[_-]?key|secret|password|token)\s*[=:]\s*['\"][^'\"]+['\"]", "description": "Hardcoded secret detected", "action": "block"},
        ],
    },
    "sysadmin-safety": {
        "description": "Block dangerous system operations that require human approval",
        "rules": [
            # === DESTRUCTIVE FILE OPERATIONS ===
            {
                "type": "regex",
                "pattern": r"rm\s+(-[a-zA-Z]*[rf][a-zA-Z]*\s+)+(/|/\*|\$HOME|~/|\$\{?HOME\}?)",
                "description": "Recursive delete of root or home directory",
                "action": "block",
                "tool": "Bash",
                "solution": "Specify exact paths to delete, never root or home recursively",
            },
            {
                "type": "regex",
                "pattern": r"rm\s+(-[a-zA-Z]*[rf][a-zA-Z]*\s+)+\.\s*$",
                "description": "Recursive delete of current directory",
                "action": "block",
                "tool": "Bash",
                "solution": "Specify exact files/folders to delete",
            },
            {
                "type": "regex",
                "pattern": r">\s*/dev/sd[a-z]|>\s*/dev/nvme|>\s*/dev/hd[a-z]",
                "description": "Direct write to disk device",
                "action": "block",
                "tool": "Bash",
                "solution": "Never write directly to block devices without explicit user confirmation",
            },
            {
                "type": "regex",
                "pattern": r"dd\s+.*of=/dev/(sd[a-z]|nvme|hd[a-z]|disk)",
                "description": "dd write to disk device",
                "action": "block",
                "tool": "Bash",
                "solution": "Disk imaging requires explicit user confirmation",
            },
            {
                "type": "regex",
                "pattern": r"mkfs\.",
                "description": "Filesystem format command",
                "action": "block",
                "tool": "Bash",
                "solution": "Formatting filesystems requires explicit user confirmation",
            },
            {
                "type": "regex",
                "pattern": r"chmod\s+(-[a-zA-Z]*\s+)*777\s",
                "description": "World-writable permissions (777)",
                "action": "warn",
                "tool": "Bash",
                "solution": "Use more restrictive permissions (755 for dirs, 644 for files)",
            },
            # === SYSTEM CONTROL ===
            {
                "type": "regex",
                "pattern": r"\b(shutdown|reboot|halt|poweroff)\b|init\s+[0-6]",
                "description": "System shutdown/reboot command",
                "action": "block",
                "tool": "Bash",
                "solution": "System power operations require explicit user confirmation",
            },
            {
                "type": "regex",
                "pattern": r"kill\s+(-9\s+)?-1\b|killall\s+(-9\s+)?(init|systemd|sshd|cron)\b",
                "description": "Kill critical system processes",
                "action": "block",
                "tool": "Bash",
                "solution": "Never kill critical system processes autonomously",
            },
            {
                "type": "regex",
                "pattern": r"systemctl\s+(stop|disable|mask)\s+(sshd|ssh|networking|network|systemd|dbus)",
                "description": "Stop critical system services",
                "action": "block",
                "tool": "Bash",
                "solution": "Stopping critical services requires explicit user confirmation",
            },
            # === SYSTEM CONFIGURATION ===
            {
                "type": "regex",
                "pattern": r"(>\s*|tee\s+)/etc/(passwd|shadow|sudoers|fstab)",
                "description": "Overwrite critical system files",
                "action": "block",
                "tool": "Bash",
                "solution": "Use visudo for sudoers, vipw for passwd - never overwrite directly",
            },
            {
                "type": "regex",
                "pattern": r"\b(usermod|useradd|userdel|groupmod|groupadd|groupdel)\b",
                "description": "User/group modification",
                "action": "warn",
                "tool": "Bash",
                "solution": "User management requires explicit user confirmation",
            },
            {
                "type": "regex",
                "pattern": r"\bpasswd\s+\w",
                "description": "Password change command",
                "action": "block",
                "tool": "Bash",
                "solution": "Password changes require explicit user confirmation",
            },
            # === NETWORK/FIREWALL ===
            {
                "type": "regex",
                "pattern": r"iptables\s+(-F|--flush)|nft\s+flush|ufw\s+disable",
                "description": "Flush or disable firewall rules",
                "action": "block",
                "tool": "Bash",
                "solution": "Firewall changes require explicit user confirmation",
            },
            {
                "type": "regex",
                "pattern": r"PermitRootLogin\s+(yes|without-password)",
                "description": "Enable SSH root login",
                "action": "block",
                "solution": "Root SSH login should remain disabled for security",
            },
            # === PACKAGE MANAGEMENT ===
            {
                "type": "regex",
                "pattern": r"(apt|apt-get|yum|dnf|pacman)\s+(remove|purge|erase).*\b(coreutils|bash|systemd|libc|glibc|kernel|grub|openssh)\b",
                "description": "Remove critical system packages",
                "action": "block",
                "tool": "Bash",
                "solution": "Never remove critical system packages",
            },
            {
                "type": "regex",
                "pattern": r"(apt|apt-get|yum|dnf)\s+(dist-upgrade|full-upgrade)",
                "description": "Full system upgrade",
                "action": "warn",
                "tool": "Bash",
                "solution": "System upgrades may cause breaking changes - requires confirmation",
            },
            # === DANGEROUS SHELL PATTERNS ===
            {
                "type": "regex",
                "pattern": r":\s*\(\s*\)\s*\{.*:\s*\|.*&.*\}",
                "description": "Fork bomb pattern detected",
                "action": "block",
                "tool": "Bash",
                "solution": "Fork bombs are destructive - never execute",
            },
            {
                "type": "regex",
                "pattern": r"(curl|wget)\s+[^|]+\|\s*(ba)?sh",
                "description": "Pipe remote script to shell",
                "action": "warn",
                "tool": "Bash",
                "solution": "Download scripts first, review content, then execute",
            },
            {
                "type": "regex",
                "pattern": r"\beval\s+.*\$\(",
                "description": "Eval with command substitution",
                "action": "warn",
                "tool": "Bash",
                "solution": "Avoid eval with dynamic content - risk of code injection",
            },
            # === GIT EXTENDED SAFETY ===
            {
                "type": "regex",
                "pattern": r"git\s+clean\s+-[a-zA-Z]*f[a-zA-Z]*d",
                "description": "Git clean with force (removes untracked files/dirs)",
                "action": "warn",
                "tool": "Bash",
                "solution": "Run 'git clean -n' first to preview what will be deleted",
            },
            {
                "type": "regex",
                "pattern": r"git\s+push\s+.*--force|git\s+push\s+-f",
                "description": "Git force push",
                "action": "block",
                "tool": "Bash",
                "solution": "Force push can destroy remote history - requires confirmation",
            },
            {
                "type": "regex",
                "pattern": r"git\s+reset\s+--hard",
                "description": "Git hard reset",
                "action": "warn",
                "tool": "Bash",
                "solution": "Hard reset discards uncommitted changes - confirm first",
            },
            # === SUDO/ROOT ESCALATION ===
            {
                "type": "regex",
                "pattern": r"echo\s+.*\|\s*sudo\s+tee\s+/",
                "description": "Pipe to sudo tee (root file write)",
                "action": "warn",
                "tool": "Bash",
                "solution": "Root file writes require explicit confirmation",
            },
            {
                "type": "regex",
                "pattern": r"sudo\s+(su|bash|sh|zsh)\s*$|sudo\s+-i\s*$",
                "description": "Escalate to root shell",
                "action": "warn",
                "tool": "Bash",
                "solution": "Use sudo for specific commands rather than root shells",
            },
            # === DATABASE OPERATIONS ===
            {
                "type": "regex",
                "pattern": r"DROP\s+(DATABASE|TABLE|SCHEMA)\s+",
                "description": "SQL DROP statement",
                "action": "block",
                "tool": "Bash",
                "solution": "Destructive database operations require explicit confirmation",
            },
            {
                "type": "regex",
                "pattern": r"TRUNCATE\s+TABLE",
                "description": "SQL TRUNCATE statement",
                "action": "warn",
                "tool": "Bash",
                "solution": "Truncating tables deletes all data - requires confirmation",
            },
            {
                "type": "regex",
                "pattern": r"DELETE\s+FROM\s+\w+\s*;|DELETE\s+FROM\s+\w+\s+WHERE\s+1\s*=\s*1",
                "description": "SQL DELETE without WHERE or always-true condition",
                "action": "block",
                "tool": "Bash",
                "solution": "DELETE must have a specific WHERE clause",
            },
            # === CONTAINER/DOCKER SAFETY ===
            {
                "type": "regex",
                "pattern": r"docker\s+system\s+prune\s+(-a|--all)",
                "description": "Docker prune all unused resources",
                "action": "warn",
                "tool": "Bash",
                "solution": "This removes all unused images, containers, and networks",
            },
            {
                "type": "regex",
                "pattern": r"docker\s+rm\s+-f\s+\$\(docker\s+ps",
                "description": "Force remove all Docker containers",
                "action": "warn",
                "tool": "Bash",
                "solution": "Removing all containers requires confirmation",
            },
            {
                "type": "regex",
                "pattern": r"--privileged|--cap-add[=\s]+ALL",
                "description": "Docker privileged mode or all capabilities",
                "action": "warn",
                "tool": "Bash",
                "solution": "Privileged containers have full host access - use specific capabilities",
            },
            # === KUBERNETES SAFETY ===
            {
                "type": "regex",
                "pattern": r"kubectl\s+delete\s+(namespace|ns)\s+",
                "description": "Delete Kubernetes namespace",
                "action": "block",
                "tool": "Bash",
                "solution": "Deleting namespaces removes all resources - requires confirmation",
            },
            {
                "type": "regex",
                "pattern": r"kubectl\s+delete\s+.*--all",
                "description": "Delete all Kubernetes resources of a type",
                "action": "block",
                "tool": "Bash",
                "solution": "Mass deletion of K8s resources requires confirmation",
            },
            # === ENVIRONMENT/SECRETS ===
            {
                "type": "regex",
                "pattern": r"export\s+(AWS_SECRET|GITHUB_TOKEN|API_KEY|DATABASE_PASSWORD)=",
                "description": "Export secrets directly in shell",
                "action": "warn",
                "tool": "Bash",
                "solution": "Use .env files or secret managers instead of inline exports",
            },
        ],
    },
}
